--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Aetheam/Skyblock_Aethteam
branches:
- Master
projects:
  Skyblock_Aethteam:
    path: ""
    libs:
      - src: Paroxity/Commando/Commando
        version: ^3.0.0
        branch: PM-4.0
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
    lint:
      phpstan: false
...
